## Generate R/zzz-iml-aliases.R: an iml_*() alias for every exported ilm_*()
## function, documented on the same help page as the function it names.
##
## Run from the package root AFTER devtools::document() has put any new export
## into NAMESPACE, then run devtools::document() again so the aliases reach
## NAMESPACE and the Rd files. tests/testthat/test-iml-aliases.R fails, naming
## this script, when an export has no alias.
##
## The same order of work as pkgdown/make_reference_index.R, which also has
## to be re-run after adding an export.

ns <- readLines("NAMESPACE")
ex <- grep("^export\\(ilm_", ns, value = TRUE)
ex <- sort(sub("^export\\((.*)\\)$", "\\1", ex))

## The Rd FILE each function is documented in, read from the \alias lines.
## Several functions share a page (ilm_plot_reduce_na is on ilm_plot_reduce's),
## so this cannot be derived from the function's own name.
rd <- list.files("man", pattern = "[.]Rd$", full.names = TRUE)
where <- character(0)
for (f in rd) {
  x <- readLines(f, warn = FALSE)
  al <- sub("^\\\\alias\\{(.*)\\}$", "\\1", grep("^\\\\alias\\{", x, value = TRUE))
  for (a in intersect(al, ex)) where[[a]] <- sub("[.]Rd$", "", basename(f))
}
miss <- setdiff(ex, names(where))
if (length(miss))
  stop("no Rd page documents: ", paste(miss, collapse = ", "),
       ". Run devtools::document() first.", call. = FALSE)

head <- c(
  "## GENERATED by dev/make_iml_aliases.R -- do not edit by hand.",
  "##",
  "## Every exported ilm_*() answers to iml_*() as well. The transposition is an",
  "## easy one to type, and \"could not find function\" at the console is",
  "## friction with nothing gained. Each alias IS the function -- the same",
  "## object, not a wrapper around it -- so its arguments, defaults,",
  "## autocompletion and error messages are exactly the ilm_* function's, and",
  "## ?iml_model opens the same help page as ?ilm_model.",
  "##",
  "## The file sorts after every ilm_*.R, so each function exists before its",
  "## alias is taken. tests/testthat/test-iml-aliases.R fails when an export has",
  "## no alias, and says to re-run the script.",
  "")
body <- unlist(lapply(ex, function(f) c(
  sprintf("#' @rdname %s", where[[f]]),
  "#' @usage NULL",
  "#' @export",
  sprintf("%s <- %s", sub("^ilm_", "iml_", f), f),
  "")))
writeLines(c(head, body), "R/zzz-iml-aliases.R")
cat(length(ex), "aliases written to R/zzz-iml-aliases.R\n")
