## Every exported ilm_*() answers to iml_*() as well -- the transposition is
## an easy one to type. The aliases are generated by dev/make_iml_aliases.R,
## and this is what notices when a new export has been added without one.

iml_exports <- function() {
  ns <- readLines(system.file("NAMESPACE", package = "illumex"))
  sub("^export\\((.*)\\)$", "\\1", grep("^export\\(", ns, value = TRUE))
}

test_that("every exported ilm_*() has an exported iml_*() alias", {
  ex <- iml_exports()
  ilm <- grep("^ilm_", ex, value = TRUE)
  want <- sub("^ilm_", "iml_", ilm)
  missing <- setdiff(want, ex)
  expect(length(missing) == 0L,
         paste0("no iml_*() alias for: ", paste(missing, collapse = ", "),
                ". Run dev/make_iml_aliases.R, then devtools::document()."))
  ## and no alias outlives the function it named
  stale <- setdiff(grep("^iml_", ex, value = TRUE), want)
  expect(length(stale) == 0L,
         paste0("iml_*() aliases with no ilm_*() behind them: ",
                paste(stale, collapse = ", "),
                ". Run dev/make_iml_aliases.R, then devtools::document()."))
})

test_that("an alias IS the function it names, not a wrapper around it", {
  ns <- asNamespace("illumex")
  ilm <- grep("^ilm_", iml_exports(), value = TRUE)
  same <- vapply(ilm, function(f)
    identical(get(f, envir = ns), get(sub("^ilm_", "iml_", f), envir = ns)),
    TRUE)
  expect_true(all(same), label = paste("identical:",
                                       paste(ilm[!same], collapse = ", ")))
  ## so its arguments are the same too, which a function(...) wrapper's
  ## would not be
  expect_identical(formals(iml_describe_all), formals(ilm_describe_all))
  ## and it gives the same answer
  d <- ilm_sim()
  expect_identical(iml_describe_all(d), ilm_describe_all(d))
})
