## GENERATED by dev/make_iml_aliases.R -- do not edit by hand.
##
## Every exported ilm_*() answers to iml_*() as well. The transposition is an
## easy one to type, and "could not find function" at the console is
## friction with nothing gained. Each alias IS the function -- the same
## object, not a wrapper around it -- so its arguments, defaults,
## autocompletion and error messages are exactly the ilm_* function's, and
## ?iml_model opens the same help page as ?ilm_model.
##
## The file sorts after every ilm_*.R, so each function exists before its
## alias is taken. tests/testthat/test-iml-aliases.R fails when an export has
## no alias, and says to re-run the script.

#' @rdname ilm_anomalous
#' @usage NULL
#' @export
iml_anomalous <- ilm_anomalous

#' @rdname ilm_anomaly
#' @usage NULL
#' @export
iml_anomaly <- ilm_anomaly

#' @rdname ilm_boot_ci
#' @usage NULL
#' @export
iml_boot_ci <- ilm_boot_ci

#' @rdname ilm_boot_diff
#' @usage NULL
#' @export
iml_boot_diff <- ilm_boot_diff

#' @rdname ilm_check_missing
#' @usage NULL
#' @export
iml_check_missing <- ilm_check_missing

#' @rdname ilm_cluster
#' @usage NULL
#' @export
iml_cluster <- ilm_cluster

#' @rdname ilm_cluster_na
#' @usage NULL
#' @export
iml_cluster_na <- ilm_cluster_na

#' @rdname ilm_copies
#' @usage NULL
#' @export
iml_copies <- ilm_copies

#' @rdname ilm_counts
#' @usage NULL
#' @export
iml_counts <- ilm_counts

#' @rdname ilm_counts_all
#' @usage NULL
#' @export
iml_counts_all <- ilm_counts_all

#' @rdname ilm_counts_tb
#' @usage NULL
#' @export
iml_counts_tb <- ilm_counts_tb

#' @rdname ilm_counts_tb_all
#' @usage NULL
#' @export
iml_counts_tb_all <- ilm_counts_tb_all

#' @rdname ilm_describe
#' @usage NULL
#' @export
iml_describe <- ilm_describe

#' @rdname ilm_describe_all
#' @usage NULL
#' @export
iml_describe_all <- ilm_describe_all

#' @rdname ilm_describe_na
#' @usage NULL
#' @export
iml_describe_na <- ilm_describe_na

#' @rdname ilm_describe_na_all
#' @usage NULL
#' @export
iml_describe_na_all <- ilm_describe_na_all

#' @rdname ilm_dupes
#' @usage NULL
#' @export
iml_dupes <- ilm_dupes

#' @rdname ilm_frame_issues
#' @usage NULL
#' @export
iml_frame_issues <- ilm_frame_issues

#' @rdname ilm_gauss_check
#' @usage NULL
#' @export
iml_gauss_check <- ilm_gauss_check

#' @rdname ilm_geom_spec
#' @usage NULL
#' @export
iml_geom_spec <- ilm_geom_spec

#' @rdname ilm_glrm
#' @usage NULL
#' @export
iml_glrm <- ilm_glrm

#' @rdname ilm_outliers
#' @usage NULL
#' @export
iml_outliers <- ilm_outliers

#' @rdname ilm_outliers_all
#' @usage NULL
#' @export
iml_outliers_all <- ilm_outliers_all

#' @rdname ilm_pick_geom
#' @usage NULL
#' @export
iml_pick_geom <- ilm_pick_geom

#' @rdname ilm_plot
#' @usage NULL
#' @export
iml_plot <- ilm_plot

#' @rdname ilm_plot_all
#' @usage NULL
#' @export
iml_plot_all <- ilm_plot_all

#' @rdname ilm_plot_anomaly
#' @usage NULL
#' @export
iml_plot_anomaly <- ilm_plot_anomaly

#' @rdname ilm_plot_bar
#' @usage NULL
#' @export
iml_plot_bar <- ilm_plot_bar

#' @rdname ilm_plot_boot_diff
#' @usage NULL
#' @export
iml_plot_boot_diff <- ilm_plot_boot_diff

#' @rdname ilm_plot_box
#' @usage NULL
#' @export
iml_plot_box <- ilm_plot_box

#' @rdname ilm_plot_c
#' @usage NULL
#' @export
iml_plot_c <- ilm_plot_c

#' @rdname ilm_plot_cluster
#' @usage NULL
#' @export
iml_plot_cluster <- ilm_plot_cluster

#' @rdname ilm_plot_cluster_gap
#' @usage NULL
#' @export
iml_plot_cluster_gap <- ilm_plot_cluster_gap

#' @rdname ilm_plot_cluster_gap
#' @usage NULL
#' @export
iml_plot_cluster_gap_na <- ilm_plot_cluster_gap_na

#' @rdname ilm_plot_cluster
#' @usage NULL
#' @export
iml_plot_cluster_na <- ilm_plot_cluster_na

#' @rdname ilm_plot_density
#' @usage NULL
#' @export
iml_plot_density <- ilm_plot_density

#' @rdname ilm_plot_histogram
#' @usage NULL
#' @export
iml_plot_histogram <- ilm_plot_histogram

#' @rdname ilm_plot_line
#' @usage NULL
#' @export
iml_plot_line <- ilm_plot_line

#' @rdname ilm_plot_missing
#' @usage NULL
#' @export
iml_plot_missing <- ilm_plot_missing

#' @rdname ilm_plot_na
#' @usage NULL
#' @export
iml_plot_na <- ilm_plot_na

#' @rdname ilm_plot_na_all
#' @usage NULL
#' @export
iml_plot_na_all <- ilm_plot_na_all

#' @rdname ilm_plot_profile
#' @usage NULL
#' @export
iml_plot_profile <- ilm_plot_profile

#' @rdname ilm_plot_profile
#' @usage NULL
#' @export
iml_plot_profile_na <- ilm_plot_profile_na

#' @rdname ilm_plot_reduce
#' @usage NULL
#' @export
iml_plot_reduce <- ilm_plot_reduce

#' @rdname ilm_plot_reduce_contrib
#' @usage NULL
#' @export
iml_plot_reduce_contrib <- ilm_plot_reduce_contrib

#' @rdname ilm_plot_reduce_contrib
#' @usage NULL
#' @export
iml_plot_reduce_contrib_na <- ilm_plot_reduce_contrib_na

#' @rdname ilm_plot_reduce
#' @usage NULL
#' @export
iml_plot_reduce_na <- ilm_plot_reduce_na

#' @rdname ilm_plot_reduce_scree
#' @usage NULL
#' @export
iml_plot_reduce_scree <- ilm_plot_reduce_scree

#' @rdname ilm_plot_reduce_scree
#' @usage NULL
#' @export
iml_plot_reduce_scree_na <- ilm_plot_reduce_scree_na

#' @rdname ilm_plot_scatter
#' @usage NULL
#' @export
iml_plot_scatter <- ilm_plot_scatter

#' @rdname ilm_plot_stat_error
#' @usage NULL
#' @export
iml_plot_stat_error <- ilm_plot_stat_error

#' @rdname ilm_plot_var
#' @usage NULL
#' @export
iml_plot_var <- ilm_plot_var

#' @rdname ilm_plot_var_all
#' @usage NULL
#' @export
iml_plot_var_all <- ilm_plot_var_all

#' @rdname ilm_plot_var_pairs
#' @usage NULL
#' @export
iml_plot_var_pairs <- ilm_plot_var_pairs

#' @rdname ilm_plot_violin
#' @usage NULL
#' @export
iml_plot_violin <- ilm_plot_violin

#' @rdname ilm_profile
#' @usage NULL
#' @export
iml_profile <- ilm_profile

#' @rdname ilm_profile_na
#' @usage NULL
#' @export
iml_profile_na <- ilm_profile_na

#' @rdname ilm_recode_errors
#' @usage NULL
#' @export
iml_recode_errors <- ilm_recode_errors

#' @rdname ilm_recode_errors_vec
#' @usage NULL
#' @export
iml_recode_errors_vec <- ilm_recode_errors_vec

#' @rdname ilm_reduce
#' @usage NULL
#' @export
iml_reduce <- ilm_reduce

#' @rdname ilm_reduce_na
#' @usage NULL
#' @export
iml_reduce_na <- ilm_reduce_na

#' @rdname ilm_sim
#' @usage NULL
#' @export
iml_sim <- ilm_sim

#' @rdname ilm_translate
#' @usage NULL
#' @export
iml_translate <- ilm_translate

#' @rdname ilm_var_contrib
#' @usage NULL
#' @export
iml_var_contrib <- ilm_var_contrib

#' @rdname ilm_wash_df
#' @usage NULL
#' @export
iml_wash_df <- ilm_wash_df

